config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :readings

  resources :catogories

  resources :trackings

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/catogory.rb
class Catogory < ActiveRecord::Base
  has_many :trackings
end

app/controllers/catogories_controller.rb
class CatogoriesController < ApplicationController
  before_action :set_catogory, only: [:show, :edit, :update, :destroy]

  # GET /catogories
  # GET /catogories.json
  def index
    @catogories = Catogory.all
  end

  # GET /catogories/1
  # GET /catogories/1.json
  def show
  end

  # GET /catogories/new
  def new
    @catogory = Catogory.new
  end

  # GET /catogories/1/edit
  def edit
  end

  # POST /catogories
  # POST /catogories.json
  def create
    @catogory = Catogory.new(catogory_params)

    respond_to do |format|
      if @catogory.save
        format.html { redirect_to @catogory, notice: 'Catogory was successfully created.' }
        format.json { render :show, status: :created, location: @catogory }
      else
        format.html { render :new }
        format.json { render json: @catogory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catogories/1
  # PATCH/PUT /catogories/1.json
  def update
    respond_to do |format|
      if @catogory.update(catogory_params)
        format.html { redirect_to @catogory, notice: 'Catogory was successfully updated.' }
        format.json { render :show, status: :ok, location: @catogory }
      else
        format.html { render :edit }
        format.json { render json: @catogory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catogories/1
  # DELETE /catogories/1.json
  def destroy
    @catogory.destroy
    respond_to do |format|
      format.html { redirect_to catogories_url, notice: 'Catogory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catogory
      @catogory = Catogory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catogory_params
      params.require(:catogory).permit(:name)
    end
end

app/helpers/catogories_helper.rb
module CatogoriesHelper
end

app/views/catogories/_form.html.erb
<%= form_for @catogory, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  catogories_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/catogories/edit.html.erb
<%- model_class = Catogory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Catogory %></h1>
</div>
<%= render :partial => 'form' %>

app/views/catogories/index.html.erb
<%- model_class = Catogory -%>
<div class="page-header">
  <h1><%=t '.title', :default => Catogory %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @catogories.each do |catogory| %>
      <tr>
        <td><%= catogory.id %></td>
        <td><%= catogory.name %></td>
        <td><%=l catogory.created_at, format: :long %></td>
        <td>
          <%= link_to catogory_path(catogory), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to catogory_path(catogory), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_catogory_path,
            :class => 'btn btn-primary' %>

app/views/catogories/new.html.erb
<%- model_class = Catogory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Catogory %></h1>
</div>
<%= render :partial => 'form' %>

app/views/catogories/show.html.erb
<%- model_class = Catogory -%>
<div class="page-header">
  <h1><%=t '.title', :default => Catogory %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @catogory.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              catogories_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_catogory_path(@catogory), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              catogory_path(@catogory),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>